services:
  backend:
    container_name: hoomes_backend
    image: pinkynrg/hoomes_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      REDIS_HOST: hoomes_redis
      REDIS_PORT: 6379
    command: poetry run python server.py
    volumes:
      - hoomes-data:/app/data
      
    depends_on:
      - redis

  worker:
    container_name: hoomes_workers
    image: pinkynrg/hoomes_backend
    restart: always
    environment:
      REDIS_HOST: hoomes_redis
      REDIS_PORT: 6379
    command: poetry run python worker.py
    volumes:
      - hoomes-data:/app/data
    depends_on:
      - redis

  redis:
    container_name: hoomes_redis
    image: redis:7.2.2
    restart: always

  frontend:
    container_name: hoomes_frontend
    image: pinkynrg/hoomes_frontend
    restart: always
    ports: 
      - "10002:80"
    depends_on:
      - backend

volumes:
  hoomes-data: