version: '3.8'
services:

  vpn:
    container_name: vpn
    hostname: vpn
    image: ghcr.io/bubuntux/nordlynx
    ports:
      - "5000:5000"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PRIVATE_KEY=$NORD_VPN_PRIVATE_KEY
      - QUERY=filters\[country_id\]=106 # ITALY
      - NET_LOCAL=192.168.0.0/16
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=1

  backend:
    container_name: hoomes_backend
    image: pinkynrg/hoomes_backend
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    network_mode: service:vpn
    command: poetry run python server.py
    restart: always
    volumes:
      - ./data.db:/app/data.db
    depends_on:
      - redis
      - vpn

  frontend:
    container_name: hoomes_frontend
    image: pinkynrg/hoomes_frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      - vpn

  worker:
    container_name: hoomes_workers
    image: pinkynrg/hoomes_backend
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    command: poetry run python worker.py
    network_mode: service:vpn
    restart: always
    volumes:
      - ./data.db:/app/data.db
    depends_on:
      - redis
      - vpn

  redis:
    container_name: redis
    image: redis:7.2.2
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn

  https:
    container_name: https
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      STAGE: 'production'
      PROXY_READ_TIMEOUT: 3600
      CLIENT_MAX_BODY_SIZE: 0
      SERVER_NAMES_HASH_BUCKET_SIZE: 64
      DOMAINS: 'hoomes.me -> http://frontend:80'
    volumes:
      - ./ssl-certs:/var/lib/https-portal