name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: hoomes.me
        ssh_private_key: ${{ secrets.HOOMES_SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.HOOMES_SSH_USER }}
        docker_compose_prefix: hoomes