name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: checking out project
        uses: actions/checkout@v2

      - name: executing docker-compose stuff on remove host
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: hoomes.me
          username: ${{ secrets.HOOMES_SSH_USER }}
          key: ${{ secrets.HOOMES_SSH_PRIVATE_KEY }}
          port: 22
          script: whoami