name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: checking out project
        uses: actions/checkout@v2

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOOMES_SSH_HOST }}
          username: ${{ secrets.HOOMES_SSH_USER }}
          key: ${{ secrets.HOOMES_SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOOMES_SSH_PORT }}
          source: "docker-compose.yml"
          target: "~/hoomes"

      - name: executing docker-compose stuff on remove host
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOOMES_SSH_HOST }}
          username: ${{ secrets.HOOMES_SSH_USER }}
          key: ${{ secrets.HOOMES_SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOOMES_SSH_PORT }}
          script: |
            cd hoomes
            echo "NORD_VPN_PRIVATE_KEY=${{ secrets.NORD_VPN_PRIVATE_KEY }}" > .env