name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: checking out project
        uses: actions/checkout@v2

      - name: executing docker-compose stuff on remove host
        uses: appleboy/ssh-action@v1.0.0
        env:
          NORD_VPN_PRIVATE_KEY: ${{ secrets.NORD_VPN_PRIVATE_KEY }}
        with:
          host: hoomes.me
          username: ${{ secrets.HOOMES_SSH_USER }}
          key: ${{ secrets.HOOMES_SSH_PRIVATE_KEY }}
          port: 22
          envs: NORD_VPN_PRIVATE_KEY
          script: |
            echo "$NORD_VPN_PRIVATE_KEY"